# Generated by Django 5.0.6 on 2024-07-19 20:05

import django.core.validators
import django.db.models.deletion
import recruit.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronyme', models.CharField(max_length=15)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('photo', models.ImageField(null=True, upload_to='ecoles/photos/')),
                ('description', models.TextField(default='')),
                ('contact', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Uniquement des chiffres', regex='^\\d+$')])),
            ],
            options={
                'verbose_name': 'Ecole',
                'verbose_name_plural': 'Ecoles',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Uniquement des chiffres', regex='^\\d+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='enseignants/photos/')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dip', 'Diplôme'), ('gde', 'Grade')], default='dip', max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150, unique=True, verbose_name='intitulé')),
                ('description', models.TextField(default='', max_length=500)),
                ('sys_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
            },
        ),
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField(default='', max_length=500)),
                ('nbr_poste', models.PositiveIntegerField(default=0)),
                ('mission', models.CharField(max_length=255)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField()),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.ecole')),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='enseignants/fichiers/', verbose_name='CV')),
                ('demande', models.ImageField(blank=True, null=True, upload_to='enseignants/photos/', verbose_name='Demande manuscrite')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='enseignants/fichiers/', verbose_name='diplome')),
                ('ifu', models.FileField(blank=True, null=True, upload_to='enseignants/fichiers/', validators=[recruit.models.file_validator], verbose_name='IFU')),
                ('rib', models.FileField(blank=True, null=True, upload_to='enseignants/fichiers/', validators=[recruit.models.file_validator], verbose_name='RIB')),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('autre', models.FileField(blank=True, null=True, upload_to='enseignants/fichiers/', validators=[recruit.models.file_validator], verbose_name='Attestations formations')),
                ('statut', models.CharField(choices=[('attente', 'En cours'), ('fini', 'Terminé')], default='attente', max_length=100)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.appel', verbose_name='école')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.enseignant')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
            },
        ),
        migrations.CreateModel(
            name='Evaluateur',
            fields=[
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Uniquement des chiffres', regex='^\\d+$')])),
                ('diplome', models.ForeignKey(limit_choices_to={'type': 'dip'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluateur_diplome', to='recruit.parametre')),
                ('grade', models.ForeignKey(limit_choices_to={'type': 'gde'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluateur_grade', to='recruit.parametre')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.specialite', verbose_name='spécialité')),
            ],
            options={
                'verbose_name': 'Evaluateur',
                'verbose_name_plural': 'Evaluateurs',
                'unique_together': {('nom', 'prenom')},
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='diplome',
            field=models.ForeignKey(limit_choices_to={'type': 'dip'}, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_diplome', to='recruit.parametre'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.ForeignKey(limit_choices_to={'type': 'gde'}, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_grade', to='recruit.parametre'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_ecole', models.PositiveIntegerField(default=0, verbose_name="Ancienneté dans l'école")),
                ('ue_spec', models.BooleanField(default=False, help_text='adéquation UE spécialité', verbose_name='Adéquation UE_Spécialité')),
                ('an_ens', models.PositiveIntegerField(default=0, help_text="Ancienneté dans l'enseignement", verbose_name='Ancienneté')),
                ('formation_justifie', models.BooleanField(default=False, help_text="Formation justifié en cas d'attestation")),
                ('exp_entreprise', models.PositiveIntegerField(default=0, help_text='Expérience en entreprise')),
                ('age', models.PositiveIntegerField(default=0)),
                ('pieces', models.CharField(choices=[('comp', 'Complet'), ('inc', 'Incomplet')], default='inc', max_length=255)),
                ('decision', models.CharField(choices=[('oui', 'Recevable'), ('revoir', 'Réservé'), ('non', 'Non recevable')], default='revoir', max_length=255, verbose_name='Décision')),
                ('observation', models.TextField(default='')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.candidature')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.departement')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.evaluateur')),
                ('grade', models.ForeignKey(limit_choices_to={'type': 'gde'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grade', to='recruit.parametre')),
                ('haut_diplome', models.ForeignKey(limit_choices_to={'type': 'dip'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_diplome', to='recruit.parametre')),
                ('spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.specialite')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.specialite'),
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('sys_name', models.CharField(max_length=20)),
                ('description', models.TextField(default='')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.departement', verbose_name='Département')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enseignant',
            unique_together={('nom', 'prenom')},
        ),
    ]
